### ISSUE TITLE
All properties list showing same image

### ISSUE THREAD

**Issue by Muhammad-Azhr** [arslbbt/optima-class#1]
![screen shot 2018-02-06 at 10 08 42 am](https://user-images.githubusercontent.com/36185021/35845529-acf678ec-0b34-11e8-8755-0b9afa28f1eb.png)
![screen shot 2018-02-06 at 11 57 22 am](https://user-images.githubusercontent.com/36185021/35845627-12de37bc-0b35-11e8-9f91-b0978f525b88.png)

**Comment by usamabinkhalil** [comment]
Fixed
